# Generated by Django 3.0.5 on 2020-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotapp',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
