# Generated by Django 3.0.5 on 2020-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20200611_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotapp',
            name='pwd',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
