# Generated by Django 3.0.5 on 2020-06-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_auto_20200611_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotapp',
            old_name='pwd',
            new_name='pw',
        ),
    ]
