# Generated by Django 3.0.5 on 2020-07-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(blank=True, max_length=255, verbose_name='app_key')),
                ('deviceid', models.CharField(blank=True, max_length=255, verbose_name='deviceid')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='message')),
                ('timestamp', models.CharField(blank=True, max_length=255, verbose_name='timestamp')),
            ],
        ),
    ]
