# Generated by Django 3.0.5 on 2020-06-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_auto_20200629_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
