# Generated by Django 2.1.4 on 2020-07-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0018_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='deviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('deviceid', models.CharField(max_length=255, verbose_name='deviceid')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
            ],
        ),
    ]
