# Generated by Django 2.1.4 on 2020-07-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0019_devicelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='deviceid',
            field=models.CharField(blank=True, max_length=255, verbose_name='deviceid'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='key',
            field=models.CharField(blank=True, max_length=255, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='message',
            field=models.CharField(blank=True, max_length=255, verbose_name='message'),
        ),
    ]
