# Generated by Django 2.1.4 on 2020-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0020_auto_20200709_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelog',
            name='key',
        ),
        migrations.AddField(
            model_name='devicelog',
            name='app_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='app_key'),
        ),
    ]
