# Generated by Django 2.1.4 on 2020-07-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0021_auto_20200709_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, verbose_name='message'),
        ),
    ]
