# Generated by Django 2.1.4 on 2020-07-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0022_devicelog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, verbose_name='timestamp'),
        ),
    ]
